name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install deps (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build libasound2-dev libx11-dev libgl1-mesa-dev

    - name: Install deps (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake ninja

    - name: Install deps (Windows)
      if: runner.os == 'Windows'
      run: choco install cmake ninja

    - name: Setup MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DUSE_SCCACHE=OFF
        cmake --build build --parallel

    - name: Test
      run: cd build && ctest --output-on-failure

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: plugin-${{ matrix.os }}
        path: build/*LinearAmplifierPlugin*
